# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

import Confirm
import Menu
import datacollection


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(400, 379)
        self.lbl_Cart = QtWidgets.QLabel(Dialog)
        self.lbl_Cart.setGeometry(QtCore.QRect(190, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_Cart.setFont(font)
        self.lbl_Cart.setObjectName("lbl_Cart")
        self.but_Back = QtWidgets.QPushButton(Dialog)
        self.but_Back.setGeometry(QtCore.QRect(10, 330, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.but_Back.setFont(font)
        self.but_Back.setObjectName("but_Back")
        self.but_Confirm = QtWidgets.QPushButton(Dialog)
        self.but_Confirm.setGeometry(QtCore.QRect(290, 330, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.but_Confirm.setFont(font)
        self.but_Confirm.setObjectName("but_Confirm")
        self.tb_Information = QtWidgets.QTableWidget(Dialog)
        self.tb_Information.setGeometry(QtCore.QRect(25, 60, 361, 261))
        self.tb_Information.setObjectName("tb_Information")
        self.tb_Information.setColumnCount(0)
        self.tb_Information.setRowCount(0)
        self.lbl_Result = QtWidgets.QLabel(Dialog)
        self.lbl_Result.setGeometry(QtCore.QRect(150, 330, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Result.setFont(font)
        self.lbl_Result.setText("")
        self.lbl_Result.setObjectName("lbl_Result")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Createtable()

        self.but_Back.clicked.connect(self.Back_Cart)
        self.but_Back.clicked.connect(Dialog.close)

        self.but_Confirm.clicked.connect(self.Confirm)
        self.but_Confirm.clicked.connect(Dialog.close)

    def Createtable(self):
        self.tb_Information.setRowCount(len(datacollection.cart))
        self.tb_Information.setColumnCount(5)

        header1 = QtWidgets.QTableWidgetItem("Menu name")
        header2 = QtWidgets.QTableWidgetItem("Price")
        header3 = QtWidgets.QTableWidgetItem("Quantity")
        header4 = QtWidgets.QTableWidgetItem("")
        header5 = QtWidgets.QTableWidgetItem("")

        self.tb_Information.setHorizontalHeaderItem(0, header1)
        self.tb_Information.setHorizontalHeaderItem(1, header2)
        self.tb_Information.setHorizontalHeaderItem(2, header3)
        self.tb_Information.setHorizontalHeaderItem(3, header4)
        self.tb_Information.setHorizontalHeaderItem(4, header5)

        row = 0
        for i in range(len(datacollection.cart)):
            self.tb_Information.setItem(row, 0, QTableWidgetItem("{}".format(datacollection.cart[i][0])))
            self.tb_Information.setItem(row, 1, QTableWidgetItem("{}".format(datacollection.cart[i][1])))
            self.tb_Information.setItem(row, 2, QTableWidgetItem("{}".format(datacollection.cart[i][2])))
            # -----------------------Button-----------------------------------------------------------
            self.minus = QtWidgets.QPushButton('-')
            self.minus.setStyleSheet("background-color: rgb(236, 157, 0);\n"
                                     "color:white;\n"
                                     "border-style:outset;")
            self.addbut = QtWidgets.QPushButton('+')
            self.addbut.setStyleSheet("background-color: rgb(0, 211, 214);\n"
                                      "color:white;\n"
                                      "border-style:outset;")
            self.tb_Information.setCellWidget(row, 3, self.minus)
            self.tb_Information.setCellWidget(row, 4, self.addbut)
            #
            self.minus.clicked.connect(self.editcart)
            self.addbut.clicked.connect(self.addquantity)
            # ------------------------------------------------------------------------

            row += 1

    def addquantity(self):
        button = QtWidgets.qApp.focusWidget()
        index = self.tb_Information.indexAt(button.pos())
        datacollection.cart[index.row()][2] += 1
        self.Createtable()

    def editcart(self):
        button = QtWidgets.qApp.focusWidget()
        index = self.tb_Information.indexAt(button.pos())
        datacollection.cart[index.row()][2] -= 1
        if datacollection.cart[index.row()][2] == 0:
            datacollection.cart.pop(index.row())
        self.Createtable()

    def Back_Cart(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Menu.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def Confirm(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Confirm.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OnlyFood"))
        self.lbl_Cart.setText(_translate("Dialog", "Cart"))
        self.but_Back.setText(_translate("Dialog", "Back"))
        self.but_Confirm.setText(_translate("Dialog", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
