# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Cart
import Menu
import datacollection


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.lbl_Confirm = QtWidgets.QLabel(Dialog)
        self.lbl_Confirm.setGeometry(QtCore.QRect(150, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_Confirm.setFont(font)
        self.lbl_Confirm.setObjectName("lbl_Confirm")
        self.but_Back = QtWidgets.QPushButton(Dialog)
        self.but_Back.setGeometry(QtCore.QRect(10, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.but_Back.setFont(font)
        self.but_Back.setObjectName("but_Back")
        self.but_Confirm = QtWidgets.QPushButton(Dialog)
        self.but_Confirm.setGeometry(QtCore.QRect(290, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.but_Confirm.setFont(font)
        self.but_Confirm.setObjectName("but_Confirm")
        self.lbl_Result = QtWidgets.QLabel(Dialog)
        self.lbl_Result.setGeometry(QtCore.QRect(140, 120, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Result.setFont(font)
        self.lbl_Result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Result.setText("Total : {}  Bath".format(datacollection.Confirm()))
        self.lbl_Result.setObjectName("lbl_Result")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-20, -30, 441, 361))
        self.frame.setStyleSheet("border-image: url(:/newPrefix/—Pngtree—elemental background of fast food_981344.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.lbl_Confirm.raise_()
        self.but_Back.raise_()
        self.but_Confirm.raise_()
        self.lbl_Result.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.but_Back.clicked.connect(self.Back_Confirm)
        self.but_Back.clicked.connect(Dialog.close)

        self.but_Confirm.clicked.connect(self.Confirm)
        self.but_Confirm.clicked.connect(Dialog.close)

    def Back_Confirm(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Cart.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def Confirm(self):
        datacollection.cart = []
        self.window = QtWidgets.QMainWindow()
        self.ui = Menu.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OnlyFood"))
        self.lbl_Confirm.setText(_translate("Dialog", "Confirm"))
        self.but_Back.setText(_translate("Dialog", "Back"))
        self.but_Confirm.setText(_translate("Dialog", "Confirm"))
import Picture


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
