# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Picture
import pymongo
import dns
from datetime import datetime
import Login

cloudDatabase = 'mongodb+srv://myAccount:peerapol1@cluster0.ws1ng.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'


class Ui_Form_Register(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 362)
        Dialog.setMaximumSize(QtCore.QSize(404, 362))
        self.lbl_Register = QtWidgets.QLabel(Dialog)
        self.lbl_Register.setGeometry(QtCore.QRect(140, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Register.setFont(font)
        self.lbl_Register.setObjectName("lbl_Register")
        self.lbl_Name = QtWidgets.QLabel(Dialog)
        self.lbl_Name.setGeometry(QtCore.QRect(30, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Name.setFont(font)
        self.lbl_Name.setObjectName("lbl_Name")
        self.lbl_Lastname = QtWidgets.QLabel(Dialog)
        self.lbl_Lastname.setGeometry(QtCore.QRect(30, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Lastname.setFont(font)
        self.lbl_Lastname.setObjectName("lbl_Lastname")
        self.lbl_Username_ID = QtWidgets.QLabel(Dialog)
        self.lbl_Username_ID.setGeometry(QtCore.QRect(30, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Username_ID.setFont(font)
        self.lbl_Username_ID.setObjectName("lbl_Username_ID")
        self.lbl_Password = QtWidgets.QLabel(Dialog)
        self.lbl_Password.setGeometry(QtCore.QRect(30, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Password.setFont(font)
        self.lbl_Password.setObjectName("lbl_Password")
        self.lbl_RePassword = QtWidgets.QLabel(Dialog)
        self.lbl_RePassword.setGeometry(QtCore.QRect(30, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_RePassword.setFont(font)
        self.lbl_RePassword.setObjectName("lbl_RePassword")
        self.lbl_Idcard = QtWidgets.QLabel(Dialog)
        self.lbl_Idcard.setGeometry(QtCore.QRect(30, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Idcard.setFont(font)
        self.lbl_Idcard.setObjectName("lbl_Idcard")
        self.txt_Name = QtWidgets.QTextEdit(Dialog)
        self.txt_Name.setGeometry(QtCore.QRect(150, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Name.setFont(font)
        self.txt_Name.setObjectName("txt_Name")
        self.txt_Lastname = QtWidgets.QTextEdit(Dialog)
        self.txt_Lastname.setGeometry(QtCore.QRect(150, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Lastname.setFont(font)
        self.txt_Lastname.setObjectName("txt_Lastname")
        self.txt_Username = QtWidgets.QTextEdit(Dialog)
        self.txt_Username.setGeometry(QtCore.QRect(150, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Username.setFont(font)
        self.txt_Username.setObjectName("txt_Username")
        self.txt_Password = QtWidgets.QLineEdit(Dialog)
        self.txt_Password.setGeometry(QtCore.QRect(150, 170, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_Password.setFont(font)
        self.txt_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_Password.setObjectName("txt_Password")
        self.txt_RePassword = QtWidgets.QLineEdit(Dialog)
        self.txt_RePassword.setGeometry(QtCore.QRect(150, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_RePassword.setFont(font)
        self.txt_RePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_RePassword.setObjectName("txt_RePassword")
        self.txt_IdCard = QtWidgets.QTextEdit(Dialog)
        self.txt_IdCard.setGeometry(QtCore.QRect(150, 250, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_IdCard.setFont(font)
        self.txt_IdCard.setObjectName("txt_IdCard")
        self.but_Register = QtWidgets.QPushButton(Dialog)
        self.but_Register.setGeometry(QtCore.QRect(150, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.but_Register.setFont(font)
        self.but_Register.setObjectName("but_Register")
        self.lbl_Result = QtWidgets.QLabel(Dialog)
        self.lbl_Result.setGeometry(QtCore.QRect(270, 300, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Result.setFont(font)
        self.lbl_Result.setText("")
        self.lbl_Result.setObjectName("lbl_Result")
        self.but_Back = QtWidgets.QPushButton(Dialog)
        self.but_Back.setGeometry(QtCore.QRect(30, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.but_Back.setFont(font)
        self.but_Back.setObjectName("but_Back")
        self.BackgroundRegis = QtWidgets.QFrame(Dialog)
        self.BackgroundRegis.setGeometry(QtCore.QRect(-11, -11, 441, 431))
        self.BackgroundRegis.setStyleSheet(
            "border-image: url(:/newPrefix/—Pngtree—elemental background of fast food_981344.png);")
        self.BackgroundRegis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundRegis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundRegis.setObjectName("BackgroundRegis")
        self.BackgroundRegis.raise_()
        self.lbl_Register.raise_()
        self.lbl_Name.raise_()
        self.lbl_Lastname.raise_()
        self.lbl_Username_ID.raise_()
        self.lbl_Password.raise_()
        self.lbl_RePassword.raise_()
        self.lbl_Idcard.raise_()
        self.txt_Name.raise_()
        self.txt_Lastname.raise_()
        self.txt_Username.raise_()
        self.txt_Password.raise_()
        self.txt_RePassword.raise_()
        self.txt_IdCard.raise_()
        self.but_Register.raise_()
        self.lbl_Result.raise_()
        self.but_Back.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        # Event Driven
        self.but_Register.clicked.connect(self.Register)
        self.but_Back.clicked.connect(self.Back_Register)
        self.but_Back.clicked.connect(Dialog.close)

    def Back_Register(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Login.Ui_OnlyFood()
        self.ui.setupUi(self.window)
        self.window.show()


    def Register(self):
        with pymongo.MongoClient(cloudDatabase) as conn:
            name = self.txt_Name.toPlainText()
            lname = self.txt_Lastname.toPlainText()
            username = self.txt_Username.toPlainText()
            password = self.txt_Password.text()
            repass = self.txt_RePassword.text()
            id = self.txt_IdCard.toPlainText()
            check = True
            db = conn.get_default_database()
            cursor = db.users.find()
            for i in cursor:
                if i['username'] == username:
                    self.lbl_Result.setText("Cant use this Username")
                    check = False
                    break
            if password != repass:
                self.lbl_Result.setText("Password Error")
                check = False
            data = {'name':name,'lname':lname,'username': username, 'password': password,'id':id, 'last_access': datetime.now()}

            if len(name) == 0:
                check = False

            if check == True:
                self.lbl_Result.setText("Register Success")
                db.users.insert_one(data)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OnlyFood"))
        self.lbl_Register.setText(_translate("Dialog", "Register"))
        self.lbl_Name.setText(_translate("Dialog", "Name"))
        self.lbl_Lastname.setText(_translate("Dialog", "Lastname"))
        self.lbl_Username_ID.setText(_translate("Dialog", "Username"))
        self.lbl_Password.setText(_translate("Dialog", "Password"))
        self.lbl_RePassword.setText(_translate("Dialog", "RePassword"))
        self.lbl_Idcard.setText(_translate("Dialog", "IdCard"))
        self.but_Register.setText(_translate("Dialog", "Register"))
        self.but_Back.setText(_translate("Dialog", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Form_Register()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
